services:
  postgres:
    image: postgres:16-alpine
    container_name: catatgaji-db
    environment:
      POSTGRES_DB: catatgaji
      POSTGRES_USER: catatgaji
      POSTGRES_PASSWORD: catatgaji
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./apps/api/src/database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U catatgaji"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: catatgaji-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
